# version format
version: 3.0.1.{build}

# branches to build
branches:
  # only build master
  only:
    - master

# build Release	
configuration: Release

skip_commits:
  message: /Update.*\.(md|txt|mp3|png|jpg|jpeg|bmp|gif)/

# restore NuGet packages before building
before_build:
- nuget restore
